### ISSUE TITLE
Does pinch works with container or stage?

### ISSUE THREAD

**Issue by gg4u** [dekimasoon/pixi-simple-gesture#2]
Hi, I would like to apply pinch and panning to stage.

I tried:

```
var stage = new PIXI.Container();

var renderer = PIXI.autoDetectRenderer(width, height, null, false, true);

gesture.default.panable( stage ); // not working

gesture.default.panable( renderer ); // nor it does


stage.on('panstart', function() {  //or render.on ()
    console.log('pan start');

    alert('YES');
  })

```
I don't see errors on the console, but simply it does not fire the function, nor with mouse nor with mobile device.

What am I doing wrong?

**Comment by dekimasoon** [comment]
Hi @gg4u ;)

I'm not sure how you load this library, but you can probably set actions like below:
```
gesture.panable(stage)   // no 'default'
```
and, I didn't try so I'm not sure either, you may need to `setArea` to your stage.

https://github.com/pixijs/pixi.js/issues/1626
http://jsfiddle.net/mk41egbt/4/

**Comment by gg4u** [comment]
Hi @dekimasoon !
I installed like : 
npm install pixi-simple-gesture --save

and load it as:
var gesture = require('pixi-simple-gesture');

if I call it like   
```
var sprite = PIXI.Sprite.fromImage('2.png');
gesture.tappable(sprite);
```

it yields errror:

```
Uncaught TypeError: gesture.tappable is not a function
    at module.exports (bundle.js:268)
    at Object.module.exports.main (bundle.js:33)
    at onload ((index):11)

```
Pixi V. 4.5.4

if I call it like gesture.defaults it does not give errors but the function does not seems to fire either..

I would like to apply pitch on whole renderer.

I am working to apply gestures to this demo:
https://github.com/anvaka/ngraph.pixi

**Comment by johnnymast** [comment]
Hi @gg4u,

I have had the same issue (don't know if its relevant but im using [Requirejs](https://requirejs.org/)) but i solved this by loading the project like this.

```javascript
const gesture = require('pixi-simple-gesture').default

// Our internal sceneManager, main is frist container on the canvas.
let main = sceneManager.main


// This works
gesture.pinchable(main, true)
```
Enjoy :)

**Comment by dekimasoon** [comment]
Thanks @johnnymast!

**Comment by johnnymast** [comment]
No problem @dekimasoon
